// This file is generated by code generation tool. DO NOT EDIT IT !!! contact uniqs@163.com for detail.

package main

const (
	Error_OK                  = 0
	Error_Unknown             = 1
	Error_Currency_Overflow   = 2
	Error_ConfigError         = 3
	Error_ParamError          = 4
	Error_ServerInternalError = 5
	Error_Currency_NotEnough  = 6
)

var (
	ErrorStringCN []string
)

func init() {
	ErrorStringCN = append(ErrorStringCN, "成功")
	ErrorStringCN = append(ErrorStringCN, "未赋值")
	ErrorStringCN = append(ErrorStringCN, "超过最大值溢出")
	ErrorStringCN = append(ErrorStringCN, "配置错误")
	ErrorStringCN = append(ErrorStringCN, "参数错误")
	ErrorStringCN = append(ErrorStringCN, "服务器内部错误")
	ErrorStringCN = append(ErrorStringCN, "货币不足")
}
